OHVDecal/Controllers/CustomerOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using OHVDecal.Models;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Options;
using OHVDecal.Helper;

namespace OHVDecal.Controllers
{
    public class CustomerOrderController : Controller
    {
        private readonly OHVDecalContext _context;
        private readonly IConfiguration configuration;
        private readonly CyberSourceHelper _cybersourceHelper;

        public CustomerOrderController(OHVDecalContext context, IConfiguration configuration,  IOptions<CyberSourceHelper> helper)
        {
            _context = context;
            this.configuration = configuration;
            this._cybersourceHelper = helper.Value;
        }

        [HttpGet]
        public IActionResult CreateOrder()
        {
            return View();
        }
                

        [HttpPost]
        public IActionResult PayForOrder(int NumberOfTags)
        {
            decimal calcAmount = NumberOfTags * 30;
            string amount = string.Format("{0:#.00}", calcAmount );

            DateTime refDatetime = DateTime.Now;
            string referenceNumber = "";
            referenceNumber += refDatetime.Year.ToString("0000");
            referenceNumber += refDatetime.Month.ToString("00");
            referenceNumber += refDatetime.Day.ToString("00");
            referenceNumber += refDatetime.Minute.ToString("00");
            referenceNumber += refDatetime.Second.ToString("00");
            referenceNumber += refDatetime.Millisecond.ToString("000");

            IDictionary<string, string> parameters = new Dictionary<string, string>();
            //dev keys
            //parameters.Add("access_key", "07f049d249e03218be56d7e10de3eb06");
            //parameters.Add("profile_id", "C746B057-3507-42F9-9544-352FD81097B4");

            parameters.Add("secret_key", _cybersourceHelper.SecretKey);
            parameters.Add("access_key", _cybersourceHelper.AccessKey);
            parameters.Add("profile_id", _cybersourceHelper.ProfileId);

            //prod keys
            //parameters.Add("access_key", "82b4a9e6c33934aabb49d29ce12aaed9");
            //parameters.Add("profile_id", "10BC4003-41BC-493B-8A90-EF7332F1C373");

            string merchCode = "OhvDecal-" + CreateGuid();
            parameters.Add("transaction_uuid", merchCode);//unique id for cybersource every transaction(?).
            parameters.Add("signed_field_names", "access_key,profile_id,transaction_uuid,signed_field_names,unsigned_field_names,signed_date_time,locale,transaction_type,reference_number,amount,currency,consumer_id,merchant_defined_data1,merchant_defined_data2");
            parameters.Add("unsigned_field_names", "");
            parameters.Add("signed_date_time", GetUTCDateTime());
            parameters.Add("locale", "en");
            parameters.Add("transaction_type", "sale");
            parameters.Add("reference_number", merchCode);   //referenceNumber); //Payments Merch Ref number ohv+guid instead of number
            parameters.Add("amount", amount);
            parameters.Add("currency", "USD");
            parameters.Add("consumer_id", "1263456");//portal account
            parameters.Add("merchant_defined_data1", "OHV Decal");
            parameters.Add("merchant_defined_data2", NumberOfTags.ToString());

            ViewBag.parameters = parameters;
            ViewBag.NumberOfTags = NumberOfTags;

            return View(_cybersourceHelper);
        }

        public string CreateGuid()
        {
            return Guid.NewGuid().ToString();
        }

        public string GetUTCDateTime()
        {
            DateTime time = DateTime.Now.ToUniversalTime();
            return time.ToString("yyyy-MM-dd'T'HH:mm:ss'Z'");
        }
    }
}

OHVDecal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using OHVDecal.Models;
using OHVDecal.ViewModels;

namespace OHVDecal.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult DecalInformation()
        {
            return View();
        }

        //[HttpPost]
        //public IActionResult DecalInformation(RequiredCheckbox requiredCheckbox)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        return View(requiredCheckbox);
        //    }
        //    return RedirectToAction("CreateOrder", "CustomerOrder");           
        //}

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult test()
        {
            OHVDecalContext db = new OHVDecalContext();
            LogInfo log = new LogInfo();
            log.Info = "Test " + DateTime.Now;
            db.Add(log);
            db.SaveChanges();
            return View();
        }
    }
}

OHVDecal/Views/Home/DecalInformation.cshtml
@model OHVDecal.ViewModels.RequiredCheckbox
@{
    ViewData["Title"] = "DecalInformation";
}

<div class="text-center">
    <h1>Decal Information</h1>
</div>
<p></p>
<div class="row">
    <div class="col-md-3"></div>

    <div class="col-md-6 text-center">
        <h3>
            I understand that a non-resident OHV decal only allows me to operate my OHV on unimproved roads and trails and I do not intend for my OHV to be street legal.
        </h3>
    </div>
    <div class="col-md-3"></div>
</div>
<p></p>
<div class="row">
    <div class="col-md-12 text-center">
        <h4>
            <a href="https://s3-us-west-2.amazonaws.com/azgfd-portal-wordpress-pantheon/wp-content/uploads/archive/OHVRequirements_LE.pdf">Understanding OHV Registration and Decal Requirements</a>
        </h4>
    </div>
    <div class="col-md-2"></div>
</div>
<div class="text-center">
    <br />
    <a asp-controller="CustomerOrder" asp-action="CreateOrder" class="btn btn-dark" style="width:400px" role="button">Click To Agree and Continue</a>
</div>

OHVDecal/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div id="google_translate_element"></div>
<div class="text-center">
    <h1>&nbsp;</h1>
    <h1 class="display-4">Non-Resident OHV Decal Registration</h1>
</div>

<div class="text-center">
    <img src="~/Images/Logo.png" class="img-fluid" alt="Responsive image" style="width:25%" />
</div>

@*<div class="text-center">
        <br />
        <a asp-controller="CustomerOrder" asp-action="CreateOrder" class="btn btn-dark" style="width:400px" role="button">Click To Begin</a>
    </div>*@

<div class="text-center">
    <br />
    <a asp-controller="Home" asp-action="DecalInformation" class="btn btn-dark" style="width:400px" role="button">Click To Begin</a>
</div>

@*<div class="text-center">
        <br />
        <br />
        <p>Learn about <a href="https://s3.amazonaws.com/azgfd-portal-wordpress/PortalImages/files/OHV/atv_brochure.pdf">Non-Resident OHV Decal Registration</a>.</p>
    </div>*@

OHVDecal/Views/Home/test.cshtml

@{
    ViewData["Title"] = "View";
}

<h1>View</h1>

